[package]
name = "neg-tw"
version = "0.1.0"
authors = ["VS Code <vscode@microsoft.com>"]

[dependencies]
yew = "0.19"
diesel = { version = "1.4.8", features = ["postgres"]}

[[bin]]
name = "neg-tw"
path = "app/src/main.rs"