[package]
name = "neg-tw"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
yew = "0.19"
chrono = "0.4"
diesel = { version = "1.4.8", features = ["postgres", "r2d2"]}