version: '3.3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - .:/var/www/app